### ISSUE TITLE
Which one is the password here?

### ISSUE THREAD

**Issue by ABSanthosh** [SqueezedSlime/mc-proxy#1]
![image](https://user-images.githubusercontent.com/24393343/146003876-8a1d9068-efa6-40ec-8e78-c0d54322f694.png)

**Comment by SqueezedSlime** [comment]
Hi,

The altening accounts only have a token, they do not have a password. In their original authenticator, which is using the original launcher and is redirecting any authentication requests to their servers, the password field does not matter.

Also your IP field is invalid. The /20 is the CIDR notation for a subnet, because the program is unaware of this it will see the IP as a domain name. Remove the /20 and your local IP is valid. 

I also updated the software to fix a bug.

Screenshot with LAN world:
![Screenshot on windows mc-proxy](https://user-images.githubusercontent.com/88858382/146219989-11507660-d737-4b81-bb45-c24c04a0db6b.PNG)


If you join the LAN world you, your real username will be hidden by the proxy and you will see instead the name of altening (or an another name from a different alt server):
![image](https://user-images.githubusercontent.com/88858382/146219449-036ce309-72ed-4c67-946c-e8c7ded4d205.png)

**Comment by ABSanthosh** [comment]
Hi

I'm mostly using EasyMc now and they have updated their auth flow. Now, their authenticator gives a password to use in the minecraft launcher. That's why I asked about the password. 

Will try with the proper destination server.

**Comment by SqueezedSlime** [comment]
Hi

EasyMC authenticator just works without that username/password from their client. 

In their example, the password field is equal to the ALT token.
![image](https://user-images.githubusercontent.com/88858382/146668959-fe1a4156-d629-4ebf-9569-83c08a4f95e2.png)

So the username field does not matter here. Instead of typing the token in the password, you can also type the alt token in the username field of your minecraft launcher and type "anything" in the password field. This proxy does not do anything with authentication servers or SSL MITM attacks. You connect to the proxy server, and the proxy server will authenticate the ALT account for the minecraft server you want to play. You do not need the EasyMC client or Altening client.

In the last update some bugs were fixed and now you can generate tokens (with recaptcha) inside the proxy without going to their site. https://github.com/SqueezedSlime/mc-proxy/releases/tag/1.3.0

**Comment by SqueezedSlime** [comment]
In their example of EasyMC
